// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_fDIpQ5mhIVjJHvXDQ7ANcbtSI4Finxo',
    appId: '1:44469235671:web:41bced657ef780c3952592',
    messagingSenderId: '44469235671',
    projectId: 'shoes-96476',
    authDomain: 'shoes-96476.firebaseapp.com',
    storageBucket: 'shoes-96476.appspot.com',
    measurementId: 'G-8Y6L4MCHQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MOW1KMt8wwQoB0KlwQCot4XxKt8O8wk',
    appId: '1:44469235671:android:a331c98613913352952592',
    messagingSenderId: '44469235671',
    projectId: 'shoes-96476',
    storageBucket: 'shoes-96476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsuODE2K-Q8xnLmxFVP6EDeySA2ZsUUE',
    appId: '1:44469235671:ios:e762a3ccd53ce8f0952592',
    messagingSenderId: '44469235671',
    projectId: 'shoes-96476',
    storageBucket: 'shoes-96476.appspot.com',
    iosClientId: '44469235671-bf69ia2ig9176ah3gimjvsuq2hp8njp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYsuODE2K-Q8xnLmxFVP6EDeySA2ZsUUE',
    appId: '1:44469235671:ios:e762a3ccd53ce8f0952592',
    messagingSenderId: '44469235671',
    projectId: 'shoes-96476',
    storageBucket: 'shoes-96476.appspot.com',
    iosClientId: '44469235671-bf69ia2ig9176ah3gimjvsuq2hp8njp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesInventory',
  );
}
